### ISSUE TITLE
Failed to send request. 0x17ab -32002

### ISSUE THREAD

**Issue by isoz** [01protocol/zo-keeper#17]
```
zo_keeper::liquidator::utils: Failed to send request. message: "Transaction simulation failed: Error processing Instruction 0: custom program error: 0x17ab", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(InstructionError(0, Custom(6059))), logs: Some(["Program Zo1ggzTUKMY5bYnDvT5mtVeZxzf2FaLTbKkmvGUhUQk invoke [1]", "Program log: Instruction: LiquidateSpotPosition", "Program log: Custom program error: 0x17ab", "Program Zo1ggzTUKMY5bYnDvT5mtVeZxzf2FaLTbKkmvGUhUQk consumed 29434 of 200000 compute units", "Program Zo1ggzTUKMY5bYnDvT5mtVeZxzf2FaLTbKkmvGUhUQk failed: custom program error: 0x17ab"]), accounts: None, units_consumed: Some(0) }). Code: -32002
```

Any idea? I keep getting this error, tried switching RPC's but it's always the same... thanks!

**Comment by CherryMan** [comment]
This isn't well documented yet, but if you look at the [IDL](https://github.com/01protocol/zo-client/blob/2b6590a446766d2980139904108cc6beafd1f2ef/src/types/zo.ts#L2553) for the `zo` program, you'll see that error code 6059 (or 0x17ab) refers to `OracleCacheStale`. This happens when the crank fails to cache a given oracle for a while, which often happens during high congestion on the network. If you get this error, it'll usually go away after a while or when there is less traffic.

**Comment by isoz** [comment]
same thing kept happening over multiple days with multiple nodes...
![image](https://user-images.githubusercontent.com/6126350/169191944-0992a9d8-5db9-4065-b18b-910d56575b21.png)

I'm running it with 'cargo r --release -- liquidator' and using env vars
